### ISSUE TITLE
Convert Github Milestones Into Zenhub Sprints

### ISSUE THREAD

**Issue by DerekRuiz** [Pyxsys/ttg-healthcheck#119]
## **What needs to be completed?**
Zenhub is discontinuing the Github milestones in favour of the Zenhub Sprint mechanism.
Convert all the Github milestones into Zenhub sprints, and move any Issue that are in the expiring milestones to the corresponding sprints.

#### **Success Criteria**
- [x] Create a Zenhub sprint for each Github milestone
- [x] Move each Issue currently in a milestone to the corresponding sprint
- [x] Add each Issue that has a sprint to the corresponding release

#### **Additional Information**
![Assign Sprint, Remove Milestone, Assign Release](https://images.zenhubusercontent.com/6137e16ed7038f0c3c0ab4dc/0519ca9e-e8ef-4d9c-b2aa-5e0fe3625b82)
