### ISSUE TITLE
[User Story] As an application user, I want the UI of the Specific Device Detail Page to be well thought out using a figma diagram

### ISSUE THREAD

**Issue by arich94** [Pyxsys/ttg-healthcheck#172]
### **Is your user story related to a problem? Please describe.**
It frustrates me when the UI of an application is not well thought out.

### **Describe the solution you'd like**
I would like the specific device detail page to be well thought out using a figma diagram, that can easily be shown for clear feedback.

### **Describe alternatives you've considered**
Simple reports on the intended UI are good, but figma offers more clarity than a report can give.

### **Additional context**
No additional context necessary.

### **Tasks**
Create figma diagrams that shows the following application functionality:
- [x] add colour/background
- [x] allow some cards/fields (CPU, Memory, etc.) to be hidden/shown when clicked
- [x] reorganize the fields to be in different tabs, but still on the same page (optional)

**Comment by j-eltayar** [comment]
Device detail page updated with new front end style. Figma diagrams  were created that show the following application functionality:
-  Add colour/background
-  Allow some cards/fields (CPU, Memory, etc.) to be hidden/shown when clicked
-  Reorganize the fields to be indifferent tabs, but still on the same page (optional)
![image](https://user-images.githubusercontent.com/45185212/146702411-96ffd250-2089-4b2d-b6bd-cfd41d5e4c4b.png)

As well an additional change:
- Adding  a process tab to one of the cards to act as a container for issue #173 
![image](https://user-images.githubusercontent.com/45185212/146702351-1b0c42d5-0ef0-45ec-962f-0d25bdce0c45.png)
